# Generated by Django 5.2.8 on 2025-12-05 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_order_delivery_date_order_delivery_planned_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='postal_code',
        ),
        migrations.AddField(
            model_name='client',
            name='adress',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
