# Generated by Django 5.2.8 on 2025-12-07 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_client_postal_code_client_adress'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='payment_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='shipping_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='shipping_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
