# Generated by Django 5.2.8 on 2025-12-27 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_orderproduct_payment_type_orderproduct_shipping_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_type',
            field=models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('paypal', 'PayPal'), ('bank_transfer', 'Bank Transfer')], default='cash', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_type',
            field=models.CharField(choices=[('store', 'Retrait en magasin'), ('home', 'Livraison à domicile')], default='store', max_length=20),
        ),
    ]
