# Generated by Django 5.2.8 on 2026-01-29 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_order_payment_type_order_shipping_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='invoice_pdf',
            field=models.FileField(blank=True, null=True, upload_to='invoices/'),
        ),
    ]
