# Generated by Django 5.2.8 on 2026-02-02 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_payment_invoice_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='invoice_sent',
            field=models.BooleanField(default=False),
        ),
    ]
