"""
Django settings for Main project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
from decouple import config
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    "localhost",
    "127.0.0.1",
]

#CORS_ALLOW_CREDENTIALS = True

CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
    "http://localhost:8080",
]

# Application definition

INSTALLED_APPS = [
    'corsheaders',
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'api',
    'rest_framework_simplejwt',

]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]



ROOT_URLCONF = 'Main.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Main.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

if config('DATABASE_URL', default=None) or (config('DB_NAME', default=None) and config('USE_POSTGRES', default=False, cast=bool)):
    # If DATABASE_URL is provided (e.g. on Heroku/Choreo) or USE_POSTGRES is True
    import dj_database_url
    DATABASES['default'] = dj_database_url.config(
        default=f"postgres://{config('DB_USER')}:{config('DB_PASSWORD')}@{config('DB_HOST')}:{config('DB_PORT')}/{config('DB_NAME')}",
        conn_max_age=600
    )


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Configuration pour les envois de mail
from decouple import config

import os

EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"

EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = 587
EMAIL_USE_TLS = True

EMAIL_HOST_USER = "yonlifidelis2@gmail.com"
EMAIL_HOST_PASSWORD = "mkrg phud bdjz qgen"

DEFAULT_FROM_EMAIL = f"DigiScia <{EMAIL_HOST_USER}>"



# Configuration Django REST Framework avec JWT
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication', 
    ),
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ]
}

from datetime import timedelta

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=300),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=1),
}



# Chemin de base du projet
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Dossier de stockage des fichiers uploadés
MEDIA_URL = '/media/' # URL pour les fichiers médias (images)
MEDIA_ROOT = os.path.join(BASE_DIR, 'media') # Chemin physique pour stocker les médias



# styling
JAZZMIN_SETTINGS = {
    "site_title": "DigiScia Admin",
    "site_header": "DigiScia",
    "site_brand": "DigiScia Admin",
    "site_logo": None,
    "welcome_sign": "Bienvenue sur la plateforme d'administration DigiScia",
    "copyright": "DigiScia",
    
    "search_model": ["auth.User", "api.Product"],

    "topmenu_links": [
        {"name": "Accueil", "url": "http://localhost:8000/admin/", "permissions": ["auth.view_user"]},
        {"name": "Site", "url": "http://localhost:5173/", "permissions": ["auth.view_user"]},
        {"model": "auth.User"},
        {"app": "api"},
    ],

    "show_sidebar": True,
    "navigation_expanded": True,
    "hide_apps": [],
    "hide_models": [],

    "order_with_respect_to": ["auth", "api"],

    "icons": {
        "auth": "fas fa-users",
        "auth.user": "fas fa-user",
        "api.Client": "fas fa-user-circle",
        "api.Category": "fas fa-tags",
        "api.Product": "fas fa-box",
        "api.Comment": "fas fa-comment",
        "api.Order": "fas fa-shopping-cart",
        "api.Payment": "fas fa-credit-card",
        "api.Subscriber": "fas fa-envelope",
    },

    "default_icon_parents": "fas fa-folder",
    "default_icon_children": "fas fa-dot-circle",

    "related_modal_active": True,
    "custom_css": None,
    "custom_js": None,
     # ✅ Enlève le pied de page avec les versions
    "show_footer": False,
    
    # Optionnel : empêche d'afficher le bouton "UI Builder" si présent
    "show_ui_builder": False,
}


